### ISSUE TITLE
How to make some changes?

### ISSUE THREAD

**Issue by giggioman00** [FoolCode/FoOlSlide#56]
Hi, I would like to change the template of the Latest releases page, but I can't find whicj page should I change in your cms.
From example, in your site this is the page I want to change: http://foolrulez.org/slide/reader/

I would like to remove all the info (for example: Vol.9 Chapter 229 by FoOlRulez, 22nd May, 2015) and so on, remove the title of every manga and replace all of this with just the thumb. If I click on the thumb I will be redirect to the main page of that manga, for example this: http://foolrulez.org/slide/reader/series/seitokai_yakuindomo/

Also, I would like to remove/disable all the social network button.

Thank you.

**Comment by george-fb** [comment]
The latest releases page is handled by `content/theme/default/views/latest.php` and the manga page by `content/theme/default/views/comic.php`

Also here is [a theme I made](https://github.com/george-fb/tiny_manga).

**Comment by giggioman00** [comment]
Thank you, is it possible to see a live demo of your theme? I would also like to change the default font.

**Comment by george-fb** [comment]
No live version, you can set up a local install, drop it in your theme folder and activate it from the admin area.
