### ISSUE TITLE
Set up load balancer, only loading half the pages

### ISSUE THREAD

**Issue by TheWhiteHunter** [FoolCode/FoOlSlide#71]
Hey, I think I have everything set up correctly but my master reader is only loading half the pages now. Is this something that takes some time to sync up the master and clients? Or is there an issue with having an https master and an http client?

I've set the client to 0% priority for now just so it works fine for my readers.

Master Settings:
![image](https://user-images.githubusercontent.com/16769601/27946504-6181d0e2-62af-11e7-8d06-dbd66c37a11e.png)

Client Settings:
![image](https://user-images.githubusercontent.com/16769601/27946518-71fc172a-62af-11e7-8cd5-2018dd291a62.png)

**Comment by oohnoitz** [comment]
The content you are trying to serve from the load balancer (client) is over HTTP on your master (HTTPS). This should be returning an mixed content warning in your browsers JS console. IMO, this functionality should even be necessary and was only implemented to fulfill a weird use-case of one of the developers. A much simpler route would just to use an actual CDN.
