### ISSUE TITLE
Can't install - Error 1364

### ISSUE THREAD

**Issue by etshy** [FoolCode/FoOlSlide#73]
Hi After enter my information in /install page I got a error 500 page, and after relod I got this

Error Number: 1364

Field 'user_data' doesn't have a default value

INSERT INTO `fs_ci_sessions` (`session_id`, `ip_address`, `user_agent`, `last_activity`) VALUES ('97c42b7b3c677ebd1e9f637deba5cc79', 'XXX-XXX-XXX-XXX', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36', 1500982192)

Filename: libraries/Session.php

Line Number: 327

Here is my sql mode
`mysql> SELECT @@sql_mode;
+------------------------+
| @@sql_mode             |
+------------------------+
| NO_ENGINE_SUBSTITUTION |
+------------------------+`

I have php 7.0.1.

Can't find why I can't install.

edit : yep, It doeasn't work at all when I select MySQL (not table created in the database) and crash when I select MySQLi (some tables created, but crash after with the message above).

Seems the install script is not working with php 7 ?

**Comment by bato3** [comment]
No, this error is produceb by MySQL and wrong table structure.
Fastest way (but probably not enough god) be add in: https://github.com/FoolCode/FoOlSlide/blob/master/application/migrations/001_Install.php#L18
`DEFAULT ''`

**Comment by etshy** [comment]
Well I just tried a new installation yesterday night, (re download the 2.3.3 and re-upload in my server) don't change anything in config or other file, and the installation worked ...
The only thing I changed was the database user. I used the root user instead of a special user I created (with all right granted on the foolslid db, though) so don't really understand why and how, but ... that worked ^^"

I'll try to reinstall on my live site later, I developped a very simple app to read manga so don't know if I'll keep my app or try again with foolslide.

I close the issue for now
